//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/CreateRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeUnitService/CreateRealTimeUnitResponse")]
        bool CreateRealTimeUnit(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/CreateRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeUnitService/CreateRealTimeUnitResponse")]
        System.Threading.Tasks.Task<bool> CreateRealTimeUnitAsync(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SetValue", ReplyAction="http://tempuri.org/IRealTimeUnitService/SetValueResponse")]
        bool SetValue(string message, string id, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SetValue", ReplyAction="http://tempuri.org/IRealTimeUnitService/SetValueResponse")]
        System.Threading.Tasks.Task<bool> SetValueAsync(string message, string id, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference1.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference1.IRealTimeUnitService>, RealTimeUnit.ServiceReference1.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateRealTimeUnit(int id, string address) {
            return base.Channel.CreateRealTimeUnit(id, address);
        }
        
        public System.Threading.Tasks.Task<bool> CreateRealTimeUnitAsync(int id, string address) {
            return base.Channel.CreateRealTimeUnitAsync(id, address);
        }
        
        public bool SetValue(string message, string id, byte[] signature) {
            return base.Channel.SetValue(message, id, signature);
        }
        
        public System.Threading.Tasks.Task<bool> SetValueAsync(string message, string id, byte[] signature) {
            return base.Channel.SetValueAsync(message, id, signature);
        }
    }
}
